Repository Mesh4all/m4ag-firmware, pull requests merged in 2021-11, with the labels that each got.

#4 docs: Create contribution templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Area: CI, Area: doc

#8 Contributing guidelines
  CONTRIBUTING.md
Labels: Area: doc, Status: ready for review

#9 docs: Add Contributors File
  CONTRIBUTORS
Labels: Status: ready for review

#11 docs: Modifying the README.md
  README.md
Labels: Area: doc, Status: ready for merge, Status: ready for review

#17 Build structure
  .gitignore
  Makefile
  boards/m4a-mb/Kconfig
  boards/m4a-mb/Makefile
  boards/m4a-mb/Makefile.dep
  boards/m4a-mb/Makefile.features
  boards/m4a-mb/Makefile.include
  boards/m4a-mb/board.c
  boards/m4a-mb/dist/openocd.cfg
  boards/m4a-mb/doc.txt
  boards/m4a-mb/include/board.h
  boards/m4a-mb/include/gpio_params.h
  boards/m4a-mb/include/periph_conf.h
  firmware/Makefile
  firmware/include/main.h
  firmware/main.c
  tests/Makefile.tests_common
  tests/driver_ds18/Makefile
  tests/driver_ds18/README.md
  tests/driver_ds18/main.c
  tests/periph_uart/Makefile
  tests/periph_uart/main.c
Labels: Area: boards, Area: doc, Area: firmware, Area: Kconfig, Area: tests, Platform: m4a-mb, Status: ready for review

#20 sh: Adding script dependencies
  dist/tools/utils/depends.sh
Labels: Area: tools, Status: ready for review
